In [77]:
import numpy as np

docs = [
    'go Bangladesh', 
    'Bangladesh Bangladesh',
    'I love Bangladesh',
    'Inquilab Zindabad',
    'go go go',
    'Messi is the best',
    'I love football',
    'football is life',
    'Inquilab is the movement',
    'Que miras bobo'
]

In [78]:
import tensorflow

In [79]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [80]:
tokenizer.fit_on_texts(docs)

In [81]:
len(tokenizer.word_index)

16

In [82]:
tokenizer.word_index

{'go': 1,
 'bangladesh': 2,
 'is': 3,
 'i': 4,
 'love': 5,
 'inquilab': 6,
 'the': 7,
 'football': 8,
 'zindabad': 9,
 'messi': 10,
 'best': 11,
 'life': 12,
 'movement': 13,
 'que': 14,
 'miras': 15,
 'bobo': 16}

In [83]:
sequences = tokenizer.texts_to_sequences(docs)

In [84]:
sequences

[[1, 2],
 [2, 2],
 [4, 5, 2],
 [6, 9],
 [1, 1, 1],
 [10, 3, 7, 11],
 [4, 5, 8],
 [8, 3, 12],
 [6, 3, 7, 13],
 [14, 15, 16]]

In [85]:
from tensorflow.keras.utils import pad_sequences



sequences = pad_sequences(sequences, padding='post')

In [86]:
sequences

array([[ 1,  2,  0,  0],
       [ 2,  2,  0,  0],
       [ 4,  5,  2,  0],
       [ 6,  9,  0,  0],
       [ 1,  1,  1,  0],
       [10,  3,  7, 11],
       [ 4,  5,  8,  0],
       [ 8,  3, 12,  0],
       [ 6,  3,  7, 13],
       [14, 15, 16,  0]], dtype=int32)

In [87]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *

model = Sequential()

model.add(Embedding(17,output_dim=2, input_length = 5))

model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_10 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [88]:
model.compile('adam', 'accuracy')

In [89]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[[[-0.03986578  0.03958632]
  [-0.0355921   0.0315897 ]
  [ 0.04416225  0.0340366 ]
  [ 0.04416225  0.0340366 ]]

 [[-0.0355921   0.0315897 ]
  [-0.0355921   0.0315897 ]
  [ 0.04416225  0.0340366 ]
  [ 0.04416225  0.0340366 ]]

 [[ 0.03913176  0.0469601 ]
  [ 0.04994338 -0.01548593]
  [-0.0355921   0.0315897 ]
  [ 0.04416225  0.0340366 ]]

 [[ 0.01776389 -0.02540537]
  [-0.04326237 -0.00672773]
  [ 0.04416225  0.0340366 ]
  [ 0.04416225  0.0340366 ]]

 [[-0.03986578  0.03958632]
  [-0.03986578  0.03958632]
  [-0.03986578  0.03958632]
  [ 0.04416225  0.0340366 ]]

 [[-0.0176941   0.02705145]
  [ 0.00992412 -0.00482865]
  [ 0.01656974  0.04644594]
  [ 0.02943205  0.0405712 ]]

 [[ 0.03913176  0.0469601 ]
  [ 0.04994338 -0.01548593]
  [ 0.04206901 -0.03078454]
  [ 0.04416225  0.0340366 ]]

 [[ 0.04206901 -0.03078454]
  [ 0.00992412 -0.00482865]
  [ 0.01752173 -0.00477153]
  [ 0.04416225  0.0340366 ]]

 [[ 0.01776389 -0.02540537]
  [ 0.00992412 -0.0048

In [94]:

from tensorflow.keras.datasets import imdb

In [95]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=5000)

In [96]:
X_train.shape

(25000,)

In [97]:
from tensorflow.keras.utils import pad_sequences

In [98]:
X_train = pad_sequences(X_train, maxlen = 50)
X_test = pad_sequences(X_test, maxlen = 50)

In [99]:
X_train.shape

(25000, 50)

In [103]:
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Embedding(10000, output_dim=2,input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [104]:
model.compile('adam', 'binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=5, batch_size=128, validation_split=0.2)

Epoch 1/5
157/157 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.5026 - loss: 0.6941 - val_accuracy: 0.4942 - val_loss: 0.6949
Epoch 2/5
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5617 - loss: 0.6843 - val_accuracy: 0.6950 - val_loss: 0.5779
Epoch 3/5
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7625 - loss: 0.4925 - val_accuracy: 0.7880 - val_loss: 0.4600
Epoch 4/5
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8421 - loss: 0.3596 - val_accuracy: 0.7860 - val_loss: 0.4827
Epoch 5/5
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8621 - loss: 0.3262 - val_accuracy: 0.7994 - val_loss: 0.4776
